[build]
builder = "NIXPACKS"

[deploy]
startCommand = "PYTHONPATH=/app:$PYTHONPATH python backend/manage.py migrate && PYTHONPATH=/app:$PYTHONPATH gunicorn backend.config.wsgi:application --bind 0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
